"""Convert the moderation-safe portrait into a compact Luau palette image."""

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "assets" / "jumpscare" / "blind-one-jumpscare-safe-v2.png"
OUTPUT = ROOT / "src" / "StarterPlayer" / "StarterPlayerScripts" / "EmbeddedJumpscareImage.luau"
WIDTH = 384
HEIGHT = 216
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"


image = Image.open(SOURCE).convert("RGB")
image = image.resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)
indexed = image.quantize(
    colors=len(ALPHABET),
    method=Image.Quantize.MEDIANCUT,
    dither=Image.Dither.FLOYDSTEINBERG,
)

raw_palette = indexed.getpalette()
used_indices = sorted(set(indexed.getdata()))
remap = {old: new for new, old in enumerate(used_indices)}
palette = []
for old in used_indices:
    start = old * 3
    red, green, blue = raw_palette[start : start + 3]
    palette.append((red << 16) | (green << 8) | blue)

pixels = list(indexed.getdata())
rows = []
for y in range(HEIGHT):
    start = y * WIDTH
    row = "".join(ALPHABET[remap[pixel]] for pixel in pixels[start : start + WIDTH])
    rows.append(row)

lines = [
    "--!strict",
    "-- Generated by assets/jumpscare/build_embedded_jumpscare.py.",
    "-- Palette-compressed so the jumpscare works without a Roblox image upload.",
    "return {",
    f"\tWidth = {WIDTH},",
    f"\tHeight = {HEIGHT},",
    f'\tAlphabet = "{ALPHABET}",',
    "\tPalette = {",
]
for color in palette:
    lines.append(f"\t\t0x{color:06X},")
lines.extend(["\t},", "\tRows = {"])
for row in rows:
    lines.append(f'\t\t"{row}",')
lines.extend(["\t},", "}", ""])

OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"Wrote {OUTPUT} ({len(palette)} colors, {WIDTH}x{HEIGHT})")
